### ISSUE TITLE
Code Annotations

### ISSUE THREAD

**Issue by smcunning** [ShaunDaneJames/Crate#21]
- [x] Each team member has submitted their code annotation branch 
- [x] Alyssa 
- [x] Shaunda
- [x] Zach
- [x] Shawn T.
- [x] Shaun J. 

_Code Annotation Requirements_ 
- Each member has submitted a branch called `code-annotations-<your name>` 
- Branches contain a list of specific files of code that will need to be updated in order to add the additional features outlined in your track 
- For each file, walk through the code and add a comment above each line/block that describes what that code is doing 
- [Submission Link](https://docs.google.com/forms/d/e/1FAIpQLSdsrSRG584ucT5McWQ6gG-te4x_hkOj1a3UOHO9CKzG0ay0Ow/viewform)

**Comment by smcunning** [comment]
My code annotations are submitted. ✅

**Comment by Shawntru** [comment]
Submitted!

**Comment by alyssajoyner** [comment]
Submitted :)
